### ISSUE TITLE
feat/#6 로그인 기능 구현

### ISSUE THREAD

**Issue by yuziwoo** [yuziwoo/29cm-mob-clone#6]
### 📄 Describe

로그인 기능 구현

### ✅ Tasks

- [x] Firebase 설치
- [x] 기본 로그인, google, 깃허브 로그인 구현
- [x] Recoil 설치 및 로그인 데이터 저장
- [x] 로그인 페이지 구현
- [x] 회원가입 페이지 구현
- [x] footer skeleton 구현
- [x] 마이페이지 구현 

### 🙋🏻 More

👍 모바일 환경에서 소셜 로그인을 테스트하기 위해 서버 배포 우선 작업 예정 / 서버 없이 모바일 환경에서 로그인이 안되네요.
